# Generated by Django 4.2.15 on 2024-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFE_REQUEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subsidiaries', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=100)),
                ('assets', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('ops_duration', models.CharField(max_length=100)),
                ('perenco_share', models.CharField(max_length=100)),
                ('create_leader', models.CharField(max_length=100)),
                ('member', models.CharField(max_length=100)),
            ],
        ),
    ]
